### ISSUE TITLE
Regarding the video encryption

### ISSUE THREAD

**Issue by chiragasawa** [codergogoi/netflix_backend_nodejs#1]
I just want to know that in  this project where you use video encryption so user will  not able do to piracy and also why you use zlib module.

**Comment by codergogoi** [comment]
It was an experiment only to show how streaming is working with user authentication. If you expect someone will do this for you FREE  it will not work that way. I think you need to search on google a bit about how encryption is working. If you find something useful which can help others rather than raising questions suggest your best solution so people can move forward to learn something new. Try to contribute something whatever you have to save humanity!

Here is a link that may guide you to understand.

https://crypto.stackexchange.com/questions/61637/real-time-video-stream-aes-encryption-with-authentication#:~:text=It%20seems%20that%20Netflix%20uses,verify%20and%20play%20the%20video.
